### ISSUE TITLE
Update for current activesupport

### ISSUE THREAD

**Issue by voidus** [sshaw/padrino_bootstrap_forms#9]
Hi,

padrino_bootstrap_forms currently still depends on activesupport ~>3.0 , which conflicts with padrino-0.13, which indirectly depends on activesupport >=3.1

**Comment by sshaw** [comment]
Glad to see this is still being used :smile: 

Have you tried to use this with Padrino 0.13?

I'm porting over [another project of mine](https://github.com/sshaw/itunes_store_transporter_web/tree/padrino_upgrade) to 0.12.5 and I tried upgrading padrino_bootstrap_forms there, it resulted in **a lot** of failures. Most of them looked to be due to the [fragile test cases](https://github.com/sshaw/padrino_bootstrap_forms/blob/master/spec/support/form_tag_helpers.rb#L45) but not :100:% sure.

Probably better to rewrite with [rspec-html-matchers](https://github.com/kucaahbe/rspec-html-matchers), though last I checked they don't have strict matching. 

Pull requests welcome :neckbeard: :exclamation:

**Comment by sshaw** [comment]
> I'm porting over another project of mine to 0.12.5 and I tried upgrading padrino_bootstrap_forms there ...

Versions of Padrino > 0.11 wont work due to [broken view helpers](https://github.com/padrino/padrino-framework/issues/1785#issuecomment-217073325).

**Comment by sshaw** [comment]
Version ~~0.1.1~~ 0.1.2 has support for Padrino >= v0.12.6 and >= v0.13.2
